# Setup
title:               Byungsoo's Blog
tagline:             'Daily log'
description:         'A record of my daily experience'
url:                 'https://obs0811.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Byungsoo Oh
  url:               
  email:             obs0811@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jemoji

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
category_dir: category/